server:
  port: ${PRODUCT_SERVICE_PORT:8092}
  forward-headers-strategy: framework
spring:
  application:
    name: ${PRODUCT_SERVICE_NAME:jvmcc-product-reactive-service}
  profiles:
    active: ${SPRING_PROFILE:development}
  cloud:
    config:
      uri: ${CLOUD_CONFIG_URI:optional:configserver:http://localhost:8888}
      username: ${CLOUD_CONFIG_USERNAME:jvmcc}
      password: ${CLOUD_CONFIG_PASSWORD:jvmcc}
  security:
    user:
      name: ${SECURITY_USERNAME:jvmcc}
      password: ${SECURITY_PASSWORD:jvmcc}
  datasource:
    url: ${MYSQL_SERVER_URL:jdbc:mysql://localhost:3306/jvmcc?verifyServerCertificate=false&useSSL=true&requireSSL=true}
    username: ${MYSQL_USERNAME:jvmcc}
    password: ${MYSQL_PASSWORD:jvmcc}
    driverClassName: com.mysql.cj.jdbc.Driver
  config:
    import: ${CLOUD_CONFIG_URI:optional:configserver:http://localhost:8888/}
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
jwt:
  secret: jvmcc
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9000/eureka/}
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
springdoc:
  swagger-ui:
    use-root-path: false
  show-actuator: true
  secret: jvmcc
product:
    url: https://www.adidas.co.uk/api/products/
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: info
    org:
      springframework: info
    com:
      jds:
        jmvcc: info