server:
  port: 8092
  forward-headers-strategy: framework
spring:
  application:
    name: jvmcc-product-service
  profiles:
    active: development
  security:
    user:
      name: jvmcc
      password: jvmcc
  datasource:
    url: jdbc:mysql://jvmcc-mysql:3306/jvmcc?verifyServerCertificate=false&useSSL=true&requireSSL=true
    username: jvmcc
    password: jvmcc
    driverClassName: com.mysql.cj.jdbc.Driver
  config:
    import: optional:configserver:http://jvmcc:jvmcc@jvmcc-config-server:8888/
  main:
    allow-bean-definition-overriding: true
  cache:
    caffeine:
      spec: expireAfterWrite=300s
  zipkin:
    base-url: http://zipkin-server:9411
feign:
  circuitbreaker:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint: 
    health: 
      showDetails: ALWAYS
  endpoints:
    web:
      exposure:
        include: 
          - metrics
          - health
          - circuitbreakers
          - circuitbreakerevents
resilience4j:
  circuitbreaker:
    configs:
      default:  
        registerHealthIndicator: true
jwt:
  secret: jvmcc
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://jvmcc-eureka-2-server.com:9000/eureka
      # defaultZone: http://jvmcc-eureka-1-server.com:9001/eureka, http://jvmcc-eureka-2-server.com:9002/eureka, http://jvmcc-eureka-3-server.com.com:9003/eureka
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
springdoc:
  swagger-ui:
    use-root-path: false
  show-actuator: true
  secret: jvmcc
product:
    url: https://www.adidas.co.uk/api/products/
logging:
  file:
    name: ${java.io.tmpdir}/application.log
  # pattern: 
  #   console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: info
    org:
      springframework: 
        cache: trace
    com:
      jds:
        jmvcc: info