server:
  port: ${PRODUCT_SERVICE_PORT:8092}
  forward-headers-strategy: framework
spring:
  application:
    name: ${PRODUCT_SERVICE_NAME:jvmcc-product-service}
  profiles:
    active: ${SPRING_PROFILE:development}
  config:
    import: ${CONFIG_SERVER_URL:optional:configserver:http://localhost:8888/}
  cloud:
    config:
      uri: ${CLOUD_CONFIG_URI:optional:configserver:http://localhost:8888}
      username: ${CLOUD_CONFIG_USERNAME:jvmcc}
      password: ${CLOUD_CONFIG_PASSWORD:jvmcc}
  main:
    allow-bean-definition-overriding: true
  cache:
    caffeine:
      spec: expireAfterWrite=300s
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
feign:
  httpclient:
    enabled: false
  circuitbreaker:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
ribbon:
  eureka:
    enabled: true
  list-of-servers: ${EUREKA_SERVERS:optional:eureka:http://localhost:9000/}
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint: 
    health: 
      showDetails: ALWAYS
  endpoints:
    web:
      exposure:
        include: 
          - metrics
          - health
          - circuitbreakers
          - circuitbreakerevents
resilience4j:
  circuitbreaker:
    configs:
      default:  
        registerHealthIndicator: true
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9000/eureka/}
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
springdoc:
  swagger-ui:
    use-root-path: false
  show-actuator: true
product:
    url: https://www.adidas.co.uk/api/products/
review:
    host: ${REVIEW_HOST:http://localhost:8091}
logging:
  level:
    root: info
    org:
      springframework: 
        cache: trace
    com:
      jds:
        jmvcc: info