server:
  port: ${PRODUCT_SERVICE_PORT:8092}
  forward-headers-strategy: framework
spring:
  application:
    name: ${PRODUCT_SERVICE_NAME:jvmcc-product-service}
  profiles:
    active: ${SPRING_PROFILE:development}
  security:
    user:
      name: ${SECURITY_USERNAME:jvmcc}
      password: ${SECURITY_PASSWORD:jvmcc}
  datasource:
    url: ${MYSQL_SERVER_URL:jdbc:mysql://localhost:3306/jvmcc?verifyServerCertificate=false&useSSL=true&requireSSL=true}
    username: ${MYSQL_USERNAME:jvmcc}
    password: ${MYSQL_PASSWORD:jvmcc}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  config:
    import: ${CONFIG_SERVER_URL:optional:configserver:http://jvmcc:jvmcc@localhost:8888/}
  main:
    allow-bean-definition-overriding: true
  cache:
    caffeine:
      spec: expireAfterWrite=300s
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
feign:
  circuitbreaker:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint: 
    health: 
      showDetails: ALWAYS
  endpoints:
    web:
      exposure:
        include: 
          - metrics
          - health
          - circuitbreakers
          - circuitbreakerevents
resilience4j:
  circuitbreaker:
    configs:
      default:  
        registerHealthIndicator: true
jwt:
  secret: jvmcc
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9000/eureka/}
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
springdoc:
  swagger-ui:
    use-root-path: false
  show-actuator: true
  secret: jvmcc
product:
    url: https://www.adidas.co.uk/api/products/
logging:
  file:
    name: ${java.io.tmpdir}/application.log
  level:
    root: info
    org:
      springframework: 
        cache: trace
    com:
      jds:
        jmvcc: info