server:
  port: 8092
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
springdoc:
  swagger-ui:
    use-root-path: true
jwt:
  secret: jvmcc
product:
    url: https://www.adidas.co.uk/api/products/
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: info
    org:
      springframework: info