version: "3.8"
services:
  jvmcc-service-discovery-1:
    container_name: jvmcc-service-discovery-1
    image: jvmcc-service-discovery:latest
    build:
      context: jvmcc-service-discovery
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILE: production
      SERVICE_DISCOVERY_PORT: 9000
      SERVICE_DISCOVERY_HOSTNAME: jvmcc-service-discovery-1
      SERVICE_DISCOVERY_NAME: jvmcc-service-discovery-1
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-2:9001/eureka
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
    ports:
      - "9000:9000"
    networks:
      - jvmcc-local
    depends_on:
      jvmcc-config-server:
        condition: service_healthy
  jvmcc-service-discovery-2:
    container_name: jvmcc-service-discovery-2
    image: jvmcc-service-discovery:latest
    build:
      context: jvmcc-service-discovery
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILE: production
      SERVICE_DISCOVERY_PORT: 9001
      SERVICE_DISCOVERY_HOSTNAME: jvmcc-service-discovery-2
      SERVICE_DISCOVERY_NAME: jvmcc-service-discovery-2
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-1:9000/eureka
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
    ports:
      - "9001:9001"
    networks:
      - jvmcc-local
    depends_on:
      jvmcc-config-server:
        condition: service_healthy
  # API Gateway container. This container is the only container exposed to the outside
  jvmcc-api-gateway-1:
    container_name: jvmcc-api-gateway-1
    image: jvmcc-api-gateway:latest
    build:
      context: jvmcc-api-gateway
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILE: production
      API_GATEWAY_PORT: 8080
      API_GATEWAY_NAME: jvmcc-api-gateway
      CLOUD_CONFIG_URI: optional:configserver:http://jvmcc-config-server:8888/
      CLOUD_CONFIG_USERNAME: jvmcc
      CLOUD_CONFIG_PASSWORD: jvmcc
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
      API_GATEWAY_USERNAME: jvmcc
      API_GATEWAY_PASSWORD: jvmcc
      API_GATEWAY_ADMIN_USERNAME: admin
      API_GATEWAY_ADMIN_PASSWORD: admin
      KEYCLOAK_ISSUER_URI: http://jvmcc-keycloak:8084/realms/jvmcc-service
      KEYCLOAK_JWK_SET_URI: http://jvmcc-keycloak:8084/token-service/realms/jvmcc-service/protocol/openid-connect/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 5s
      retries: 3
    ports:
      - "8080:8080"
    depends_on:
      - jvmcc-config-server
      - jvmcc-zipkin
      - jvmcc-service-discovery-1
      - jvmcc-service-discovery-2
      - jvmcc-keycloak
    networks:
      - jvmcc-local
  jvmcc-api-gateway-2:
    container_name: jvmcc-api-gateway-2
    image: jvmcc-api-gateway:latest
    build:
      context: jvmcc-api-gateway
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILE: production
      API_GATEWAY_PORT: 8081
      API_GATEWAY_NAME: jvmcc-api-gateway
      CLOUD_CONFIG_URI: optional:configserver:http://jvmcc-config-server:8888/
      CLOUD_CONFIG_USERNAME: jvmcc
      CLOUD_CONFIG_PASSWORD: jvmcc
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
      API_GATEWAY_USERNAME: jvmcc
      API_GATEWAY_PASSWORD: jvmcc
      API_GATEWAY_ADMIN_USERNAME: admin
      API_GATEWAY_ADMIN_PASSWORD: admin
      KEYCLOAK_ISSUER_URI: http://jvmcc-keycloak:8084/realms/jvmcc-service
      KEYCLOAK_JWK_SET_URI: http://jvmcc-keycloak:8084/token-service/realms/jvmcc-service/protocol/openid-connect/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 1m30s
      timeout: 5s
      retries: 3
    ports:
      - "8081:8081"
    depends_on:
      - jvmcc-config-server
      - jvmcc-zipkin
      - jvmcc-service-discovery-1
      - jvmcc-service-discovery-2
      - jvmcc-keycloak
    networks:
      - jvmcc-local
  jvmcc-product-service-1:
    container_name: jvmcc-product-service-1
    image: jvmcc-product-service:latest
    build:
      context: jvmcc-product-service
      dockerfile: Dockerfile
    environment:
      PRODUCT_SERVICE_PORT: 8091
      SPRING_PROFILE: production
      EUREKA_CLIENT_ENABLED: true
      EUREKA_INSTANCE_HOSTNAME: jvmcc-product-service-1
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      CLOUD_CONFIG_URI: optional:configserver:http://jvmcc-config-server:8888/
      CLOUD_CONFIG_USERNAME: jvmcc
      CLOUD_CONFIG_PASSWORD: jvmcc
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
      REVIEW_HOST: http://jvmcc-review-service-1:8093, http://jvmcc-review-service-2:8094
      EUREKA_SERVERS: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
    deploy:
        restart_policy:
                condition: on-failure
    ports:
      - "8091:8091"
    depends_on:
      - jvmcc-config-server
      - jvmcc-service-discovery-1
      - jvmcc-service-discovery-2
      - jvmcc-review-service-1
      - jvmcc-review-service-2
      - jvmcc-zipkin
    profiles:
      - non-reactive
    networks:
      - jvmcc-local
  jvmcc-product-service-2:
    container_name: jvmcc-product-service-2
    image: jvmcc-product-service:latest
    build:
      context: jvmcc-product-service
      dockerfile: Dockerfile
    environment:
      PRODUCT_SERVICE_PORT: 8092
      SPRING_PROFILE: production
      EUREKA_CLIENT_ENABLED: true
      EUREKA_INSTANCE_HOSTNAME: jvmcc-product-service-2
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      CLOUD_CONFIG_URI: optional:configserver:http://jvmcc-config-server:8888/
      CLOUD_CONFIG_USERNAME: jvmcc
      CLOUD_CONFIG_PASSWORD: jvmcc
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
      REVIEW_HOST: http://jvmcc-review-service-1:8093, http://jvmcc-review-service-2:8094
      EUREKA_SERVERS: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - jvmcc-config-server
      - jvmcc-service-discovery-1
      - jvmcc-service-discovery-2
      - jvmcc-review-service-1
      - jvmcc-review-service-2
      - jvmcc-zipkin
    profiles:
      - non-reactive
    networks:
      - jvmcc-local
  jvmcc-product-reactive-service:
    container_name: jvmcc-product-reactive-service
    image: jvmcc-product-reactive-service:latest
    build:
      context: jvmcc-product-reactive-service
      dockerfile: Dockerfile
    environment:
      PRODUCT_SERVICE_PORT: 8092
      SPRING_PROFILE: production
      EUREKA_CLIENT_ENABLED: true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      CLOUD_CONFIG_URI: optional:configserver:http://jvmcc-config-server:8888/
      CLOUD_CONFIG_USERNAME: jvmcc
      CLOUD_CONFIG_PASSWORD: jvmcc
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
    ports:
      - "8092:8092"
    deploy:
        restart_policy:
                condition: on-failure
    depends_on:
      - jvmcc-service-discovery-1
      - jvmcc-service-discovery-2
      - jvmcc-ldap-server
      - zookeeper
      - kafka
      - jvmcc-zipkin
    profiles:
      - reactive
    networks:
      - jvmcc-local
  jvmcc-review-service-1:
    container_name: jvmcc-review-service-1
    image: jvmcc-review-service:latest
    build:
      context: jvmcc-review-service
      dockerfile: Dockerfile
    environment:
      REVIEW_SERVICE_PORT: 8093
      SPRING_PROFILE: production
      EUREKA_CLIENT_ENABLED: true
      EUREKA_INSTANCE_HOSTNAME: jvmcc-review-service-1
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      CLOUD_CONFIG_URI: optional:configserver:http://jvmcc-config-server:8888/
      CLOUD_CONFIG_USERNAME: jvmcc
      CLOUD_CONFIG_PASSWORD: jvmcc
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
      MYSQL_SERVER_URL: jdbc:mysql://jvmcc-mysql:3306/jvmcc?verifyServerCertificate=false&useSSL=true&requireSSL=true
      MYSQL_USERNAME: jvmcc
      MYSQL_PASSWORD: jvmcc
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: true
      EUREKA_CLIENT_FETCH_REGISTRY: true
      JWK_SET_URI: http://jvmcc-keycloak:8084/auth/realms/jvmcc-service/protocol/openid-connect/certs
    ports:
      - "8093:8093"
    deploy:
        restart_policy:
                condition: on-failure
    depends_on:
      - jvmcc-config-server
      - jvmcc-service-discovery-1
      - jvmcc-service-discovery-2
      - jvmcc-mysql
      - jvmcc-zipkin
    profiles:
      - non-reactive
    networks:
      - jvmcc-local
  jvmcc-review-service-2:
    container_name: jvmcc-review-service-2
    image: jvmcc-review-service:latest
    build:
      context: jvmcc-review-service
      dockerfile: Dockerfile
    environment:
      REVIEW_SERVICE_PORT: 8094
      SPRING_PROFILE: production
      EUREKA_CLIENT_ENABLED: true
      EUREKA_INSTANCE_HOSTNAME: jvmcc-review-service-2
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      CLOUD_CONFIG_URI: optional:configserver:http://jvmcc-config-server:8888/
      CLOUD_CONFIG_USERNAME: jvmcc
      CLOUD_CONFIG_PASSWORD: jvmcc
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
      MYSQL_SERVER_URL: jdbc:mysql://jvmcc-mysql:3306/jvmcc?verifyServerCertificate=false&useSSL=true&requireSSL=true
      MYSQL_USERNAME: jvmcc
      MYSQL_PASSWORD: jvmcc
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: true
      EUREKA_CLIENT_FETCH_REGISTRY: true
      JWK_SET_URI: http://jvmcc-keycloak:8084/auth/realms/jvmcc-service/protocol/openid-connect/certs
    ports:
      - "8094:8094"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - jvmcc-config-server
      - jvmcc-service-discovery-1
      - jvmcc-service-discovery-2
      - jvmcc-mysql
      - jvmcc-zipkin
    profiles:
      - non-reactive
    networks:
      - jvmcc-local
  jvmcc-review-reactive-service:
    container_name: jvmcc-review-reactive-service
    image: jvmcc-review-reactive-service:latest
    build:
      context: jvmcc-review-reactive-service
      dockerfile: Dockerfile
    environment:
      REVIEW_SERVICE_PORT: 8091
      SPRING_PROFILE: production
      EUREKA_CLIENT_ENABLED: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      CLOUD_CONFIG_URI: optional:configserver:http://jvmcc-config-server:8888/
      CLOUD_CONFIG_USERNAME: jvmcc
      CLOUD_CONFIG_PASSWORD: jvmcc
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
      SECURITY_USERNAME: jvmcc
      SECURITY_PASSWORD: jvmcc
      SPRING_DATA_MONGODB_HOST: mongo
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
    ports:
      - "8091:8091"
    deploy:
        restart_policy:
                condition: on-failure
    depends_on:
      - jvmcc-config-server
      - jvmcc-service-discovery-1
      - jvmcc-service-discovery-2
      - jvmcc-mongodb
      - jvmcc-ldap-server
      - zookeeper
      - kafka
      - jvmcc-zipkin
    profiles:
      - reactive
    networks:
      - jvmcc-local
  jvmcc-config-server:
    container_name: jvmcc-config-server
    image: jvmcc-config-server:latest
    build:
      context: jvmcc-config-server
      dockerfile: Dockerfile
    environment:
      CONFIG_SERVER_PORT: 8888
      CONFIG_APPLICATION_NAME: jvmcc-config-server
      SPRING_PROFILE: production
      EUREKA_CLIENT_ENABLED: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://jvmcc-service-discovery-1:9000/eureka/,http://jvmcc-service-discovery-2:9001/eureka/
      ZIPKIN_SERVER_URL: http://jvmcc-zipkin:9411
      SECURITY_USERNAME: jvmcc
      SECURITY_PASSWORD: jvmcc
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-u jvmcc:jvmcc", "http://jvmcc-config-server:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - jvmcc-local
  jvmcc-zipkin:
    container_name: jvmcc-zipkin
    image: jvmcc-zipkin:latest
    build:
      context: jvmcc-zipkin
      dockerfile: Dockerfile
    environment:
      ZIPKIN_PORT: 9411
      SPRING_PROFILE: production
      CLOUD_CONFIG_URI: optional:configserver:http://jvmcc-config-server:8888/
      CLOUD_CONFIG_USERNAME: jvmcc
      CLOUD_CONFIG_PASSWORD: jvmcc
    ports:
      - "9411:9411"
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["/docker-bin/docker-healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - jvmcc-local
  jvmcc-mysql:
    container_name: jvmcc-mysql
    image: mysql/mysql-server:8.0
    build:
      context: jvmcc-mysql
      dockerfile: Dockerfile 
    ports:
      - 3306:3306
    volumes:
      - ./jvmcc-mysql/initSQL.sql:/docker-entrypoint-initdb.d/initSQL.sql
    healthcheck:
      test: ["CMD", "mysql -ujvmcc -pjvmcc  -e 'SELECT count(*) FROM review' jvmcc"]
      timeout: 20s
      retries: 10
    profiles:
      - non-reactive
    networks:
      - jvmcc-local
  jvmcc-mongodb:
    container_name: jvmcc-mongodb
    image: jvmcc-mongodb
    build:
      context: jvmcc-mongodb
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    profiles:
      - reactive
    networks:
      - jvmcc-local
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    profiles:
      - reactive
    networks:
      - jvmcc-local
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: OUTSIDE://kafka:9092,INSIDE://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://kafka:9092,INSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - zookeeper
    profiles:
      - reactive
    networks:
      - jvmcc-local
  jvmcc-keycloak:
    image: jvmcc-keycloak
    container_name: jvmcc-keycloak
    build:
      context: jvmcc-keycloak
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_ADMIN: jvmcc
      KEYCLOAK_ADMIN_PASSWORD: jvmcc
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/jvmcc-realm.json
    ports:
      - "8084:8084"
    # The realm import is giving an error, we'll have to fix it later.
    # command:
    #   - start-dev
    #   - --import-realm
    healthcheck:
      test: ["CMD-SHELL", "curl http://jvmcc-keycloak:8084/auth/realms/jvmcc-service"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 1m
    networks:
      - jvmcc-local
  jvmcc-ldap-server:
    image: jvmcc-ldap-server
    container_name: jvmcc-ldap-server
    build:
      context: jvmcc-ldap-server
      dockerfile: Dockerfile
    environment:
      LDAP_ORGANISATION: jvmcc
      LDAP_DOMAIN: jvmcc.com
      LDAP_ADMIN_PASSWORD: admin
      LDAP_LOG_LEVEL: 64
    ports:
      - 389:389
      - 636:636
    networks:
      - jvmcc-local
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=jvmcc-ldap-server
    ports:
      - "6443:443"
    depends_on:
      - jvmcc-ldap-server
    networks:
      - jvmcc-local
    profiles:
      - ldap
volumes:
  # mysql_data:
  mongodata:
networks:
  jvmcc-local:
    external: false
      