version: "3.8"
services:
  jvmcc-service-discovery:
    container_name: jvmcc-service-discovery
    image: dalamar/jvmcc-service-discovery:latest
    ports:
      - "8761:8761"
  # API Gateway container. This container is the only container exposed to the outside
  jvmcc-api-gateway:
    container_name: jvmcc-api-gateway
    image: dalamar/jvmcc-api-gateway:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://jvmcc-service-discovery:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - jvmcc-service-discovery
    links:
      - jvmcc-service-discovery
  jvmcc-product-service:
    container_name: jvmcc-product-service
    image: dalamar/jvmcc-product-service:latest
    environment:
        - JAVA_OPTS="-Dspring.profiles.active=docker"
        - SPRING_CONFIG_URI="http://jvmcc-config-server:9000"
    ports:
      - "8081:8081"
    deploy:
        restart_policy:
                condition: on-failure
    depends_on:
      - jvmcc-service-discovery
      - openldap
    links:
      - jvmcc-service-discovery
    profiles:
      - non-reactive
  jvmcc-product-reactive-service:
    container_name: jvmcc-product-reactive-service
    image: dalamar/jvmcc-product-reactive-service:latest
    environment:
        - JAVA_OPTS="-Dspring.profiles.active=docker"
        - SPRING_CONFIG_URI="http://jvmcc-config-server:9000"
    ports:
      - "8081:8081"
    deploy:
        restart_policy:
                condition: on-failure
    depends_on:
      - jvmcc-service-discovery
      - openldap
      - zookeeper
      - kafka
    links:
      - jvmcc-service-discovery
    profiles:
      - reactive
  jvmcc-review-service:
      container_name: jvmcc-review-service
      image: dalamar/jvmcc-review-service:latest
      environment:
        - JAVA_OPTS="-Dspring.profiles.active=docker"
        - SPRING_CONFIG_URI="http://jvmcc-config-server:9000"
      ports:
        - "8082:8082"
      deploy:
          restart_policy:
                  condition: on-failure
      depends_on:
        - jvmcc-service-discovery
        - jvmcc-mysql
        - openldap
      links:
        - jvmcc-service-discovery
      profiles:
        - non-reactive
  jvmcc-review-reactive-service:
      container_name: jvmcc-review-reactive-service
      image: dalamar/jvmcc-review-reactive-service:latest
      environment:
        - JAVA_OPTS="-Dspring.profiles.active=docker"
        - SPRING_CONFIG_URI="http://jvmcc-config-server:9000"
        - SPRING_DATA_MONGODB_HOST=mongo
      ports:
        - "8082:8082"
      deploy:
          restart_policy:
                  condition: on-failure
      depends_on:
        - jvmcc-service-discovery
        - jvmcc-mongodb
        - openldap
        - zookeeper
        - kafka
      links:
        - jvmcc-service-discovery
      profiles:
        - reactive
  jvmcc-mysql:
    image: dalamar/jvmcc-mysql
    environment:
        - JAVA_OPTS="-Dspring.profiles.active=docker"
        - SPRING_CONFIG_URI="http://jvmcc-config-server:9000"
        - MYSQL_USER=jvmcc
        - MYSQL_PASSWORD=jvmcc
        - MYSQL_DATABASE=jvmcc
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_ROOT_HOST='%'  
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    command: mysqld --init-file="/initSQL.sql"
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - non-reactive
  jvmcc-mongodb:
    container_name: mongodbreviews
    build:
      context: ./mongoData
    image: adidas/mongodb:1.0.0
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    profiles:
      - reactive
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    profiles:
      - reactive
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: OUTSIDE://kafka:9092,INSIDE://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://kafka:9092,INSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - zookeeper
    profiles:
      - reactive
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL_HOST=mysql
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - "8080:8084"
    command: start-dev
    depends_on:
      - jvmcc-mysql
    healthcheck:
      test: "curl -f http://localhost:8084/admin || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="J. Daniel Sobrado"
      - LDAP_DOMAIN=jvmcc.com
    ports:
      - "389:389"
volumes:
  mysql_data:
  mysql_config:
  mongodata: