server:
  port: ${CONFIG_SERVER_PORT:8888}
spring:
  application:
    name: jvmcc
  profiles:
    active: development
  security:
    user:
      name: jvmcc
      password: jvmcc
  cloud:
    config:
      server:
        git:
          uri: https://github.com/danielsobrado/spring-cloud-kafka-microservices
          searchPaths: 'config-repo'
          clone-on-start: true
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
info:
  component: JVMCC Configuration Server
encrypt:
  keyStore:
    location: classpath:jvmcc-keystore.p12
    password: jvmcc-secret
    alias: jvmcc
    secret: jvmcc-secret
    type: PKCS12
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: info
    org:
      springframework: info
    com:
      jds:
        jmvcc: info