server:
  port: ${API_GATEWAY_PORT:8080}
  ssl:
    enabled: true
    key-alias: jvmcc
    key-store-password: jvmcc-secret
    key-store: classpath:jvmcc-keystore.p12
    key-store-type: PKCS12
security:
  basicAuth:
    user:
      username: ${API_GATEWAY_USERNAME:jvmcc}
      password: ${API_GATEWAY_PASSWORD:jvmcc}
    admin:
      username: ${API_GATEWAY_ADMIN_USERNAME:admin}
      password: ${API_GATEWAY_ADMIN_PASSWORD:admin}
spring:
  main:
    web-application-type: reactive
  application:
    name: ${API_GATEWAY_NAME:jvmcc-api-gateway}
  profiles:
    active: ${SPRING_PROFILE:development}
  security:
    oauth2:
      client:
        provider:
          jvmcc-keycloak-provider:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8084/realms/jvmcc-service}
        registration:
          keycloak-spring-gateway-client:
            provider: jvmcc-keycloak-provider
            scope: openid
            client-id: jvmcc-1
            client-secret:  xpRFSuPkc0xnJPjx96Y88xYeHSRUySD0
            authorization-grant-type: client_credentials
  cloud:
    config:
      uri: ${CLOUD_CONFIG_URI:optional:configserver:http://localhost:8888}
      username: ${CLOUD_CONFIG_USERNAME:jvmcc}
      password: ${CLOUD_CONFIG_PASSWORD:jvmcc}
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        connect-timeout: 2000 # 2s
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      discovery:
        locator:
          enabled: true
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException
            backoff:
              factor: 2
      routes:
        - id: jvmcc-product-service
          uri: lb://jvmcc-product-service
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward://product-fallback
                enabled: true
        - id: jvmcc-review-service-read
          uri: lb://jvmcc-review-service
          predicates:
            - Method=GET
          filters:
            - name: CircuitBreaker
              args:
                name: reviewCircuitBreaker
                fallbackUri: forward://review-fallback
                enabled: true
        - id: jvmcc-review-service-write
          uri: lb://jvmcc-review-service
          predicates:
            - Path=/review/save/**
            - Path=/review/update/**
            - Path=/review/delete/**
            - Method=PUT
            - Method=POST
            - Method=DELETE
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: reviewCircuitBreaker
                fallbackUri: forward://review-fallback
                enabled: true

  config:
    import: ${CLOUD_CONFIG_URI:optional:configserver:http://localhost:8888/}
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9000/eureka/}
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: DEBUG
          security:
            web: DEBUG