spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: jvmcc-product-service
          uri: lb://jvmcc-product-service
          predicates:
            - Path=/product**
        - id: jvmcc-review-service
          uri: lb://jvmcc-review-service
          predicates:
            - Path=/review**
    kubernetes:
      enabled: false
server:
  port: ${app_port}
  ssl:
    enabled: true
    key-alias: jvmcc
    key-store-password: jvmcc-secret
    key-store: classpath:jvmcc-keystore.p12
    key-store-type: PKCS12
eureka:
  client:
    serviceUrl:
    # defaultZone: http://jvmcc-default-eureka-server.com:9000/eureka
      defaultZone: http://jvmcc-eureka-1-server.com:9001/eureka, http://jvmcc-eureka-2-server.com:9002/eureka, http://jvmcc-eureka-3-server.com.com:9003/eureka
management:
  endpoint:
    gateway:
      enabled: true
      uri: /management/gateway
  endpoints:
    web:
      exposure:
        include: gateway