spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: jvmcc-product-service
          uri: lb://jvmcc-product-service
          predicates:
            - Path=/api/product**
        - id: jvmcc-review-service
          uri: lb://jvmcc-review-service
          predicates:
            - Path=/api/review**
    kubernetes:
      enabled: false
  application:
    name: api-gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}