spring:
  application:
    name: jvmcc-service-discovery
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
    nonSecurePortEnabled: false
    securePortEnabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:https://127.0.0.1:8761/eureka}
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org:
      springframework:
        security: DEBUG