
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
  application:
    name: jvmcc-service-discovery
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
server:
  port: 8761
eureka:
  instance:
    hostname: ${SERVICE_DISCOVERY_HOSTNAME:jvmcc-default-eureka-server.com}
    nonSecurePortEnabled: false
    securePortEnabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${SERVICE_DISCOVERY_HOSTNAME:https://localhost:9000/eureka}
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org:
      springframework:
        security: DEBUG