---
# To operate a single instance in standalone mode, this default profile is used:
spring:
  profiles: 
    active: ${SPRING_PROFILE:development}
  application:
    name: ${SERVICE_DISCOVERY_NAME:jvmcc-service-discovery}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
server:
  port: ${SERVICE_DISCOVERY_PORT:9000}
eureka:
  instance:
    hostname: ${SERVICE_DISCOVERY_HOSTNAME:jvmcc-default-eureka-server.com}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://jvmcc-eureka-server.com:9000/eureka/    
