---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
  application:
    name: jvmcc-service-discovery
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  zipkin:
    base-url: http://zipkin-server:9411
server:
  port: 9000  
eureka:
  instance:
    hostname: jvmcc-default-eureka-server.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    
 
---
spring:
  profiles: jvmcc-eureka-1
  application:
    name: jvmcc-eureka-server-clustered
  zipkin:
    base-url: http://zipkin-server:9411
server:
  port: 9001  
eureka:
  instance:
    hostname: jvmcc-eureka-1-server.com    
  client:
    registerWithEureka: true
    fetchRegistry: true       
    serviceUrl:
      defaultZone: http://jvmcc-eureka-2-server.com:9002/eureka/,http://jvmcc-eureka-3-server.com:9003/eureka/
 
---
spring:
  profiles: jvmcc-eureka-2
  application:
    name: jvmcc-eureka-server-clustered  
  zipkin:
    base-url: http://zipkin-server:9411 
server:
  port: 9002
eureka:
  instance:
    hostname: jvmcc-eureka-2-server.com      
  client:
    registerWithEureka: true
    fetchRegistry: true       
    serviceUrl:
      defaultZone: http://jvmcc-eureka-1-server.com:9001/eureka/,http://jvmcc-eureka-3-server.com:9003/eureka/
 
---
spring:
  profiles: jvmcc-eureka-3
  application:
    name: jvmcc-eureka-server-clustered  
  zipkin:
    base-url: http://zipkin-server:9411
server:
  port: 9003
eureka:
  instance:
    hostname: jvmcc-eureka-3-server.com    
  client:
    registerWithEureka: true
    fetchRegistry: true   
    serviceUrl:
      defaultZone: http://jvmcc-eureka-1-server.com:9001/eureka/,http://jvmcc-eureka-2-server.com:9002/eureka/