---
# To operate a single instance in standalone mode, this default profile is used:
spring:
  profiles: 
    active: ${SPRING_PROFILE:development}
  application:
    name: ${SERVICE_DISCOVERY_NAME:jvmcc-service-discovery}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
  cloud:
    config:
      uri: ${CLOUD_CONFIG_URI:http://localhost:8888}
      username: ${CLOUD_CONFIG_USERNAME:jvmcc}
      password: ${CLOUD_CONFIG_PASSWORD:jvmcc}
server:
  port: ${SERVICE_DISCOVERY_PORT:9000}
eureka:
  instance:
    hostname: ${SERVICE_DISCOVERY_HOSTNAME:jvmcc-service-discovery}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9000/eureka/}
