server:
  port: 9411
spring:
  application:
    name: jvmcc-zipkin-server
  profiles:
    active: development
  cloud:
    config:
      name: jvmcc-zipkin-server
      discovery:
        service-id: config
        enabled: true
      username: jvmcc
      password: jvmcc
  security:
    user:
      name: jvmcc
      password: jvmcc
info:
  component: JVMCC Zipkin Server
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: info
    org:
      springframework: info
    com:
      jds:
        jmvcc: info