server:
  port: 8091
  forward-headers-strategy: framework
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jvmcc?verifyServerCertificate=false&useSSL=true&requireSSL=true
    username: jvmcc
    password: jvmcc
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  application:
    name: jvmcc-review-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
security:
  basicAuth:  
    username: jvmcc
    password: jvmcc
jwt:
  secret: jvmcc
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
springdoc:
  swagger-ui:
    use-root-path: false
  show-actuator: true
keycloak:
  enabled: false
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"