server:
  port: ${REVIEW_SERVICE_PORT:8091}
  forward-headers-strategy: framework
spring:
  profiles:
    active: ${SPRING_PROFILE:development}
  application:
    name: ${REVIEW_SERVICE_NAME:jvmcc-review-service}
  security:
    user:
      name: ${SECURITY_USERNAME:jvmcc}
      password: ${SECURITY_PASSWORD:jvmcc}
  datasource:
    url: ${MYSQL_SERVER_URL:jdbc:mysql://localhost:3306/jvmcc?verifyServerCertificate=false&useSSL=true&requireSSL=true}
    username: ${MYSQL_USERNAME:jvmcc}
    password: ${MYSQL_PASSWORD:jvmcc}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  config:
    import: ${CONFIG_SERVER_URL:optional:configserver:http://jvmcc:jvmcc@localhost:8888/}
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}
jwt:
  secret: jvmcc
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9000/eureka/}
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
springdoc:
  swagger-ui:
    use-root-path: false
  show-actuator: true
keycloak:
  enabled: false
logging:
  # pattern: 
    # console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: info
    org:
      springframework: 
        cache: trace
    com:
      jds:
        jmvcc: info