server:
  port: ${REVIEW_SERVICE_PORT:8091}
  forward-headers-strategy: framework
review:
  service:
    error:
      path: /review/error
    api:
      version: 1.0
spring:
  application:
    name: ${REVIEW_SERVICE_NAME:jvmcc-review-service}
  profiles:
    active: ${SPRING_PROFILE:development}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8084/realms/jvmcc-service/protocol/openid-connect/certs}
  config:
    import: ${CLOUD_CONFIG_URI:optional:configserver:http://localhost:8888/}
  cloud:  
    config:
      uri: ${CLOUD_CONFIG_URI:optional:configserver:http://localhost:8888}
      username: ${CLOUD_CONFIG_USERNAME:jvmcc}
      password: ${CLOUD_CONFIG_PASSWORD:jvmcc}
  datasource:
    url: ${MYSQL_SERVER_URL:jdbc:mysql://localhost:3306/jvmcc?verifyServerCertificate=false&useSSL=true&requireSSL=true}
    username: ${MYSQL_USERNAME:jvmcc}
    password: ${MYSQL_PASSWORD:jvmcc}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9000/eureka/}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
springdoc:
  swagger-ui:
    use-root-path: false
  show-actuator: true
keycloak:
  auth-server-url: http://localhost:8084/auth/
  resource: jvmcc-services
  credentials:
    secret : xpRFSuPkc0xnJPjx96Y88xYeHSRUySD0
  use-resource-role-mappings : true
  principal-attribute: preferred_username
  bearer-only: true
  realm: jvmcc-services
logging:
  # pattern: 
    # console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: info
    org:
      springframework: 
        cache: trace
        security: debug
    com:
      jds:
        jmvcc: info