info:
  component: JVMCC Configuration Server
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/danielsobrado/spring-cloud-kafka-microservices/tree/main/config-repo
          clone-on-start: true
  security:
    user:
      name: root
      password: jvmcc
encrypt:
  keyStore:
    location: classpath:jvmcc-keystore.p12
    password: jvmcc-secret
    alias: jvmcc
    secret: jvmcc-secret
    type: PKCS12
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG