spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jvmcc?verifyServerCertificate=false&useSSL=true&requireSSL=true
    username: jvmcc
    password: jvmcc
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
  application:
    name: jvmcc-review-crud
  cloud:
    kubernetes:
      enabled: false
server:
  port: 8083
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
springfox:
  documentation:
    enabled: true
jwt:
  secret: jvmcc